apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - manager_config.yaml
  name: -config
images:
- name: controller
  newName: retvari/dcontroller
  newTag: latest
- name: dcontroller
  newName: l7mp/dcontroller
  newTag: latest
