apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: -leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dcontroller-leader-election-role
subjects:
- kind: ServiceAccount
  name: dcontroller-account
  namespace: dcontroller-system
