apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dcontroller-system
resources:
- ../rbac
- ../crd
- namespace.yaml
namePrefix: dcontroller
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - manager_config.yaml
  name: -config
