# operator that stores pods in a view to avoid the envtest API server messing with our pod status
apiVersion: dcontroller.io/v1alpha1
kind: Operator
metadata:
  name: svc-health-operator
spec:
  controllers:
    - name: pod-health-monitor
      sources:
        - kind: PodView
      pipeline:
        "@aggregate":
          - "@project":
              metadata:
                name: "$.metadata.labels['app']"
                namespace: "$.metadata.namespace"
              pods:
                podName: "$.metadata.name"
                ready: "$.status.conditions[?(@.type=='Ready')].status"
          - "@gather":
              # Key: group by service (name + namespace)
              - "@concat":
                  - "$.metadata.name"
                  - "--"
                  - "$.metadata.namespace"
              # Value: collapse the pods fields into a list (contains ready status)
              - "$.pods"
      target:
        kind: HealthView
        type: Updater

    - name: svc-health-monitor
      sources:
        - kind: HealthView
        - apiGroup: ""
          kind: Service
      pipeline:
        "@join":
          "@and":
            - "@eq": ["$.HealthView.metadata.name", "$.Service.metadata.name"]
            - "@eq": ["$.HealthView.metadata.namespace", "$.Service.metadata.namespace"]
        "@aggregate":
          - "@project":
              metadata:
                name: "$.Service.metadata.name"
                namespace: "$.Service.metadata.namespace"
                annotations:
                  "dcontroller.io/pod-ready":
                    "@concat":
                      - "@string":
                          "@len":
                            "@filter":
                              - "@eq": ["$$.ready", "True"]
                              - "$.HealthView.pods"
                      - "/"
                      - "@string":
                          "@len": "$.HealthView.pods"
      target:
        apiGroup: ""
        kind: Service
        type: Patcher
